### ISSUE TITLE
zpool encryption with keylocation=file:///C:\file1.key is failing as regex.c is not implemented

### ISSUE THREAD

**Issue by datacore-rm** [openzfsonwindows/openzfs#100] opened 2022-06-24 10:59 UTC
/* Fill me in when we want regex support */
int
regexec(const regex_t *restrict preg, const char *restrict string,
    size_t nmatch, regmatch_t pmatch[restrict], int eflags)
{
	return (0);
}

-------------
libzfs_crypto.c
---------------
zfs_prop_parse_keylocation(...){
   ...
   regexec(...)
}

**Comment by lundman** [comment] 2022-06-24 11:10
That's the one, I think maybe we can check illumos sources if there is a light implementation we can use (since CDDL), or BSD maybe.. can be an external dependency as well, but it is annoying to have a lot of those :)

**Comment by sskras** [comment] 2022-06-24 11:57
I wonder if it's easy to find out namely what libs did OpenZFS uses both on illumos and on FreeBSD just by looking at the source.

**Comment by sskras** [comment] 2022-06-25 07:03
man pages from illumOS and FreeBSD seems to be very similar, FWIW:
https://illumos.org/man/3C/regexec
https://www.freebsd.org/cgi/man.cgi?query=regexec&sektion=3

(After skimming through them I noticed the FreeBSD adds `REG_POSIX` which is missing on illumOS)

Now the appropriate sources looks similar too:
https://github.com/illumos/illumos-gate/blob/master/usr/src/lib/libc/port/regex/regexec.c#L1
https://github.com/freebsd/freebsd-src/blob/master/lib/libc/regex/regexec.c#L1

But judging by their (scarce) history they have clearly a bit different timing. Since 2006 the file on illumOS received only 4 updates:

> Commits on Jun 12, 2017 [8355 need **libc regex tests**](https://github.com/illumos/illumos-gate/commit/490fea6b98d609ce9ae1306209c80bb255b84c95) yuripv authored and **hrosenfeld** committed
> Commits on Jun 12, 2017 [8354 **sync** regcomp(3C) **with upstream**](https://github.com/illumos/illumos-gate/commit/7641c5eab2e15e87eafc318a09f2bd5c6f968607) yuripv authored and **hrosenfeld** committed
> Commits on Oct 8, 2010 [8 libc locale work needs updated license files](https://github.com/illumos/illumos-gate/commit/6b5e5868e7ebf1aff3a5abd7d0c4ef0e5fbf3648) Garrett D'Amore committed
> Commits on Jul 30, 2010 [2 We need a fully open libc (no libc_i18n)](https://github.com/illumos/illumos-gate/commit/4297a3b0d0a35d80f86fff155e288e885a100e6d) Garrett D'Amore committed

And FreeBSD received 5 of them:

> Commits on Nov 20, 2017 [General further adoption of SPDX licensing ID tags.](https://github.com/freebsd/freebsd-src/commit/872b698bd4a1bfc0bf008c09228e6fd238809c75) pgiffuni committed
> Commits on Apr 24, 2017 [regex: unsign and constify some variables.](https://github.com/freebsd/freebsd-src/commit/e9abc6e2be47336b6ab525c20d941e6464bd0b4f) pgiffuni committed
> Commits on Mar 1, 2017 [Renumber copyright clause 4](https://github.com/freebsd/freebsd-src/commit/7e6cabd06e6caa6a02eeb86308dc0cb3f27e10da) bsdimp committed
> Commits on Jun 11, 2007 [Diff reduction against other *BSDs: ANSIfy function](https://github.com/freebsd/freebsd-src/commit/f848dcc6bb7ba3884539039e80a8a4f70eb3f23d) delphij committed
> Commits on Jan 9, 2007 [Per Regents of the University of Calfornia letter, remove advertising](https://github.com/freebsd/freebsd-src/commit/cd1f140ae4a14278c07e6788221df20328a3fe56) bsdimp

Now if you look at the bolded commits, code in the upper one comes directly from NetBSD. And the guy mentioned is Hans Rosenfeld who also happens to maintain NetBSD port-vax:
https://www.netbsd.org/people/developers.html#hans

So maybe this hints that the illumOS libc code was brought from NetBSD?

---

NetBSD case follows:
https://man.netbsd.org/regex.3
https://github.com/NetBSD/src/blob/trunk/lib/libc/regex/regexec.c#L1

The commit history is really more active:

> Commits on Feb 26, 2021 [Arrange for tools build](https://github.com/NetBSD/src/commit/b23833c67d5d06c77ba5b52bc8cb545667ee2ebd) zoulasc committed
> Commits on Feb 25, 2021 [Add glue to disable locale code in order to be smaller.](https://github.com/NetBSD/src/commit/7f28d45241b9538e4e8d40f553ab5540407836a1) zoulasc committed
> Commits on Feb 24, 2021 [reduce casts](https://github.com/NetBSD/src/commit/509372ee8348cac971d63321ee0b1b81282d1857) zoulasc committed
> Commits on Feb 24, 2021 [**sync with FreeBSD**:](https://github.com/NetBSD/src/commit/bfebdf2c643a82fdcdd30777e262587ad110fbbe) zoulasc committed
> Commits on Mar 13, 2012 [PR/45989: Martin Husemann: lint invocation does include -w only on i386](https://github.com/NetBSD/src/commit/e826745eae06e6b784fe362c9161f351d58701b0) zoulasc committed
> Commits on Feb 12, 2009 [sign-compare fixes](https://github.com/NetBSD/src/commit/64d3d6de80c635e19e8fa78f14a65bc59b06e4b8) lukem committed
> Commits on Feb 10, 2007 [Rearrange headers for better portability.](https://github.com/NetBSD/src/commit/931a89e75ca782516d9fd7659daab3592ebd3a7b) junyoung authored and junyoung committed
> Commits on Feb 8, 2007 [ANSIfy.](https://github.com/NetBSD/src/commit/9641e3f094fb3682301343b1fa582a12f28177ca) junyoung authored and junyoung committed

And the bolded commit has a description:

> \- NLS support
> \- GNU extensions
> \- bug fixes

This is confirmed by the `REG_GNU` being mentioned in the man page (which isn't found in previous two man pages).

So it looks like implementation of `regexec()` in NetBSD is most cross-platform and up-to date. And its file is the biggest one: 254 lines against 235 on FreeBSD and 225 on illumOS.

Maybe it even serves as an upstream for illumOS (this needs to be verified with their developers).

So I would go for NetBSD implementation. My two cents.

**Comment by sskras** [comment] 2022-06-25 07:16
Well FreeBSD seems to also have another implementation called `regex(3)`:
https://github.com/freebsd/freebsd-src/commit/b37f6c9805edb4b89f0a8c2b78f78a3dcfc0647b

But I see no actual code here, only some Makefile-magic and GNU-related tests being added. So maybe it's not work thinking of.

**Comment by lundman** [comment] 2022-06-25 07:22
Yeah, Unix has had regex in (or around) libc since "ye olde" days, just not something Windows had.  If you are not in a hurry, I can throw something in next week, or if you are eager, file a PR

**Comment by sskras** [comment] 2022-06-25 07:30
PS. Then there is friendly MIT-licensed implementation from **musl**:
https://github.com/bminor/musl/blob/master/src/regex/regexec.c#L1

FWIW, the file seems to be a lot bigger, 1028 lines!

**Comment by lundman** [comment] 2022-06-28 07:48
Started on illumos regex.c but they use TSDs, which is a pain. I'll try FreeBSD, they don't appear to use tsds.

**Comment by sskras** [comment] 2022-06-28 09:57
What is a TSD? And why not start right from NetBSD=)?

**Comment by andrewc12** [comment] 2022-07-07 05:31
This is what I get when trying the regex branch at the moment
https://github.com/openzfsonwindows/openzfs/commit/2f148e917b8de38d62cfe5e80a9328cb56bcaca7

```dd if=/dev/urandom bs=32 count=1 of=file1.key```

```
zpool.exe create -f -O casesensitivity=insensitive -O normalization=formD  -O compression=zstd -O atime=off -o ashift=12 -O encryption=aes-256-ccm -O keylocation=file:///C:\file1.key -O keyformat=raw tank PHYSICALDRIVE2 PHYSICALDRIVE3 PHYSICALDRIVE4
```
```
...
working on dev '#1048576#21464350720#\\?\PHYSICALDRIVE4'
setting path here '/dev/physicaldrive4'
setting physpath here '#1048576#21464350720#\\?\PHYSICALDRIVE4'
cannot create 'tank': Failed to open key material file: Invalid argument
```

**Comment by andrewc12** [comment] 2022-07-07 05:39
lundman suggested I try ```file:////?/C:/file1.key```

```
PS C:\Users\User> zpool.exe create -f -O casesensitivity=insensitive -O normalization=formD  -O compression=zstd -O atime=off -o ashift=12 -O encryption=aes-256-ccm -O keylocation=file:////?/C:/file1.key -O keyformat=raw tank PHYSICALDRIVE2 PHYSICALDRIVE3 PHYSICALDRIVE4
```

It works.

```
...
working on dev '#1048576#21464350720#\\?\PHYSICALDRIVE4'
setting path here '/dev/physicaldrive4'
setting physpath here '#1048576#21464350720#\\?\PHYSICALDRIVE4'
key file:////?/C:/file1.key
PS C:\Users\User>
```
Just ignore that last part. I was printing the string to check to make sure it wasn't getting mangled.

**Comment by datacore-rm** [comment] 2022-07-10 14:58
Regex implementation is still required or this issue can be closed?

**Comment by andrewc12** [comment] 2022-07-10 15:14
@datacore-rm It's implemented in https://github.com/openzfsonwindows/openzfs/tree/regex and creating encrypted pools with a keyfile works.
So it could be closed.

**Comment by andrewc12** [comment] 2022-07-20 01:48
@datacore-rm It's implemented. Can you close this.

**Closed** 2022-07-20 05:20 UTC

**Comment by sskras** [comment] 2022-07-20 10:14
@andrewc12 commented [10 days ago](#issuecomment-1179746753):

> @datacore-rm It's implemented in https://github.com/openzfsonwindows/openzfs/tree/regex and creating encrypted pools with a keyfile works. So it could be closed.

Yay! Another cheers to @lundman:
https://github.com/openzfsonwindows/openzfs/commit/9c8f536a5b794da911e07cc631eafa60f50709e1
